steps:
  # Supprimer le service Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run services delete ${_SERVICE_NAME} --region=${_REGION} --quiet || echo "Cloud Run service not found"

  # Supprimer l'image de l'Artifact Registry
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud artifacts docker images delete ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME} --delete-tags --quiet || echo "Image not found"

substitutions:
  _PROJECT_ID: "gcp-devops-451014"
  _REGION: "europe-southwest1"
  _SERVICE_NAME: "cloud-run-cicd"
  _LOCATION: "europe-southwest1-docker.pkg.dev"
  _REPOSITORY_NAME: "europe-southwest1-docker.pkg.dev"
  _IMAGE_NAME: "repo-3-image"

options:
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s
