steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-southwest1-docker.pkg.dev/gcp-devops-451014/my-repo-madrid/repo-3-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-southwest1-docker.pkg.dev/gcp-devops-451014/my-repo-madrid/repo-3-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-run-cicd', '--image', 'europe-southwest1-docker.pkg.dev/gcp-devops-451014/my-repo-madrid/repo-3-image', '--region', 'us-central1', '--allow-unauthenticated']
images:
- europe-southwest1-docker.pkg.dev/gcp-devops-451014/my-repo-madrid/repo-3-image
options:
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s
